const data = {
  products: [
    {
      _id: "1",
      name: "dastband black",
      category: "dastband",
      image: "/images/Screenshot_1.jpg",
      price: 120,
      brand: "yamani",
      rating: 4,
      numReviews: 10,
      description: "high quality dastband",
    },
    {
      _id: "2",
      name: "dastband black zan",
      category: "dastband",
      image: "/images/Screenshot_2.jpg",
      price: 130,
      brand: "irani",
      rating: 3.5,
      numReviews: 12,
      description: "high quality dastband zan",
    },
    {
      _id: "3",
      name: "gooswareh gold",
      category: "gooswareh",
      image: "/images/Screenshot_8.jpg",
      price: 200,
      brand: "irani",
      rating: 3,
      numReviews: 4,
      description: "high quality gooswareh",
    },
    {
      _id: "4",
      name: "gireh moo",
      category: "gireh",
      image: "/images/Screenshot_7.jpg",
      price: 12,
      brand: "araqi",
      rating: 2,
      numReviews: 15,
      description: "high quality gireh",
    },
    {
      _id: "5",
      name: "einak zard",
      category: "einak",
      image: "/images/Screenshot_11.jpg",
      price: 90,
      brand: "irani",
      rating: 4.5,
      numReviews: 7,
      description: "high quality einak",
    },
    {
      _id: "6",
      name: "persing gold",
      category: "persing",
      image: "/images/Screenshot_15.jpg",
      price: 30,
      brand: "american",
      rating: 3.5,
      numReviews: 15,
      description: "high quality persing",
    },
  ],
};
export default data;
